### ISSUE TITLE
Use with FeathersUI/Starling

### ISSUE THREAD

**Issue by cmdaniel** [myflashlab/barcode-ANE#22] opened 2016-09-14 16:25 UTC
Hi,

We are trying the BarCode ANE, but we use FeathersUI.
The windows saying "Demo Version" opens but unfortunately the camera doesn't.

The sample that you provided worked properly but it doesn't use Feathers/Starling.

Is the BarCode ANE compatible with FeathersUI?
What we need to do to implement it?

Thank you,
Daniel

**Comment by myflashlab** [comment] 2016-09-15 06:05
Let me guess, you are trying this on iOS, right? if so, you need to stop Starling before opening the camera. when returning back from the camera, you need to restart the Starling back of course.

**Comment by jamesgomes** [comment] 2016-09-16 13:22
Hi,

We create a project to test and we could not make it work.
We are testing on Android.

Can you help us ?
Follow the project link.

https://github.com/jamesgomes/Feathes3.0_ANE_barcode

Thank you,
James

**Comment by myflashlab** [comment] 2016-09-17 09:42
alright, I think I found the problem. check [this](https://github.com/myflashlab/barcode-ANE#demo-apk) out:

> NOTICE: the demo ANE works only after you hit the "OK" button in the dialog which opens. in your tests make sure that you are NOT calling other ANE methods prior to hitting the "OK" button.

Considering that you are using the demo ANE, you cannot call the ```open()``` method prior to closing the dialog box! You could do that with the commercial ANE but not the demo ANE.

Let me know if this solves your question?

P.S  considering that you are on Android, you can skip freezing the Starling. But it's still a good idea to freeze Starling when the camera opens.

**Comment by myflashlab** [comment] 2016-09-27 11:06
Please update us about this if the problem is now fixed?

**Closed** 2016-10-14 12:25 UTC
